### PR TITLE
Add back the quick start page

### PR DESCRIPTION
**Pull request by kakkoyun**

### CODE REVIEW

**Comment by brancz** [comment]
I think the style of this page worked well when it was our landing page, but I think it's confusing that we have the landing page and this. Could we make this page feel more like the other docs pages?

**Comment by kakkoyun** [comment]
> I think the style of this page worked well when it was our landing page, but I think it's confusing that we have the landing page and this. Could we make this page feel more like the other docs pages?

I can give it a try, by adding the sidebar or directly embedding this component to an mdx page.

**Comment by kakkoyun** [comment]
@brancz PTAL :) I removed the custom components and used existing docs for the quick start page.

**Comment by brancz** [comment]
Left a couple of comments using Vercel

**Comment by metalmatze** [comment]
If we end up merging this, I'm happy to remove that Download button from the header again. 
We should just make sure it's obvious and easy to get started and download Parca.

**Comment by kakkoyun** [comment]
> If we end up merging this, I'm happy to remove that Download button from the header again. We should just make sure it's obvious and easy to get started and download Parca.

@metalmatze We can update the links on the landing page to point to this page. WDYT?

**Comment by kakkoyun** [comment]
@metalmatze https://github.com/parca-dev/landing-page/pull/16

**Comment by brancz** [comment]
Love it! lgtm

**Pull request merged**
